$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
Bundler.require


Motion::Project::App.setup do |app|
  app.name = 'TableViewCell'
  app.files_dependencies 'app/app_delegate.rb' => 'app/styles/cell_style.rb'
end
