$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.icons = ['icon_iphone.png', 'icon_ipad.png', 'icon_iphone_retina.png', 'icon_ipad_retina.png']
  app.name = 'ThisAndThat'
  app.prerendered_icon = true
  app.identifier = 'com.colinta.thought4'
  app.device_family = [:iphone, :ipad]
end
