# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
Bundler.require


Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'crittercism'

  app.vendor_project('vendor/CrittercismSDK', :static,
        :headers_dir => 'vendor/CrittercismSDK')
  app.frameworks << 'SystemConfiguration'
  app.frameworks << 'Crittercism'
end
